### ISSUE TITLE
Failing to install the module 

### ISSUE THREAD

**Issue by femishan** [galkahana/HummusJS#100]
Hi,

 I am unable to install Hummus  in my nodejs application .  I am using  Windows 7 and I have not installed  Microsoft visual studio in my laptop.

This is the message from npm:
npm ERR! hummus@1.0.60 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.60 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the hummus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hummus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls hummus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\apps\testtwilio\npm-debug.log

C:\apps\testtwilio>npm install node-pre-gyp
node-pre-gyp@0.6.30 node_modules\node-pre-gyp
├── semver@5.3.0
├── nopt@3.0.6 (abbrev@1.0.9)
├── rc@1.1.6 (ini@1.3.4, deep-extend@0.4.1, strip-json-comments@1.0.4, minimist@
1.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── tar@2.2.1 (inherits@2.0.1, block-stream@0.0.9, fstream@1.0.10)
├── tar-pack@3.1.4 (uid-number@0.0.6, once@1.3.3, readable-stream@2.1.5, fstream
@1.0.10, fstream-ignore@1.0.5)
├── rimraf@2.5.4 (glob@7.0.6)
├── npmlog@4.0.0 (set-blocking@2.0.0, console-control-strings@1.1.0, are-we-ther
e-yet@1.1.2, gauge@2.6.0)
└── request@2.74.0 (tunnel-agent@0.4.3, forever-agent@0.6.1, oauth-sign@0.8.2, a
ws-sign2@0.6.0, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, aws4@1
.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.3.
1, qs@6.2.1, node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.11, bl@1.1.2
, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6, form-data@1.0.1)

C:\apps\testtwilio>npm install hummus
\
> hummus@1.0.60 install C:\apps\testtwilio\node_modules\hummus
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://hummus.s3-us-west-2.amazonaws.com/h
ummus/v1.0.60/node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.60 and node@4.4.4
(node-v46 ABI) (falling back to source compile with node-gyp)

C:\apps\testtwilio\node_modules\hummus>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\apps\testtwilio\node_modules\hummus>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\apps\testtwil
io\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:
\apps\testtwilio\node_modules\hummus\binding )  else (node "" configure --fallba
ck-to-build --module=C:\apps\testtwilio\node_modules\hummus\binding\hummus.node
--module_name=hummus --module_path=C:\apps\testtwilio\node_modules\hummus\bindin
g )

C:\apps\testtwilio\node_modules\hummus>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\apps\testtwilio\n
ode_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:\app
s\testtwilio\node_modules\hummus\binding )  else (node "" build --fallback-to-bu
ild --module=C:\apps\testtwilio\node_modules\hummus\binding\hummus.node --module
_name=hummus --module_path=C:\apps\testtwilio\node_modules\hummus\binding )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
ack-to-build" "--module=C:\\apps\\testtwilio\\node_modules\\hummus\\binding\\hum
mus.node" "--module_name=hummus" "--module_path=C:\\apps\\testtwilio\\node_modul
es\\hummus\\binding"
gyp ERR! cwd C:\apps\testtwilio\node_modules\hummus
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=C:\apps\testtwilio\node_modules\hummus\binding\hummus.node --m
odule_name=hummus --module_path=C:\apps\testtwilio\node_modules\hummus\binding'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\apps\testtwilio\node
_modules\hummus\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\apps\\testt
wilio\\node_modules\\hummus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "ins
tall" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\apps\testtwilio\node_modules\hummus
node-pre-gyp ERR! node -v v4.4.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\apps\testt
wilio\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path
=C:\apps\testtwilio\node_modules\hummus\binding' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "hummus"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! hummus@1.0.60 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.60 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the hummus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hummus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls hummus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\apps\testtwilio\npm-debug.log

C:\apps\testtwilio>

C:\apps\testtwilio>npm install hummus
\
> hummus@1.0.60 install C:\apps\testtwilio\node_modules\hummus
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://hummus.s3-us-west-2.amazonaws.com/h
ummus/v1.0.60/node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.60 and node@4.4.4
(node-v46 ABI) (falling back to source compile with node-gyp)

C:\apps\testtwilio\node_modules\hummus>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\apps\testtwilio\node_modules\hummus>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\apps\testtwil
io\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:
\apps\testtwilio\node_modules\hummus\binding )  else (node "" configure --fallba
ck-to-build --module=C:\apps\testtwilio\node_modules\hummus\binding\hummus.node
--module_name=hummus --module_path=C:\apps\testtwilio\node_modules\hummus\bindin
g )

C:\apps\testtwilio\node_modules\hummus>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\apps\testtwilio\n
ode_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:\app
s\testtwilio\node_modules\hummus\binding )  else (node "" build --fallback-to-bu
ild --module=C:\apps\testtwilio\node_modules\hummus\binding\hummus.node --module
_name=hummus --module_path=C:\apps\testtwilio\node_modules\hummus\binding )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\apps\testtwilio\node_modules\hummus\build\binding.
sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
ack-to-build" "--module=C:\\apps\\testtwilio\\node_modules\\hummus\\binding\\hum
mus.node" "--module_name=hummus" "--module_path=C:\\apps\\testtwilio\\node_modul
es\\hummus\\binding"
gyp ERR! cwd C:\apps\testtwilio\node_modules\hummus
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=C:\apps\testtwilio\node_modules\hummus\binding\hummus.node --m
odule_name=hummus --module_path=C:\apps\testtwilio\node_modules\hummus\binding'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\apps\testtwilio\node
_modules\hummus\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\apps\\testt
wilio\\node_modules\\hummus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "ins
tall" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\apps\testtwilio\node_modules\hummus
node-pre-gyp ERR! node -v v4.4.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\apps\testt
wilio\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path
=C:\apps\testtwilio\node_modules\hummus\binding' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "hummus"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! hummus@1.0.60 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.60 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the hummus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hummus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls hummus
npm ERR! There is likely additional logging output above.

Please assist to fix this issue!

**Comment by galkahana** [comment]
easy one, install msvc, gcc, or some sort of compiler. hummus ain't no javascript

**Comment by femishan** [comment]
Thanks.  I am successfully installed the  node module.   Also  I am trying to modify the  existing PDF content  which is in base64 format.  So far in the documentation , it supports only for file and stream type PDF. Is there anything available to support base64  format.

**Comment by galkahana** [comment]
no, as base64 is not something of PDF, but rather a general matter (as would be if the pdf is in a zip file). you probably mean that whatever content you have is base64 decoded. in that case just find something that decodes the file/string from base 64. i reckon you'll find something here -https://nodejs.org/api/buffer.html

**Comment by jos1337** [comment]
I have the same issue, node is falling back and builing with node-gyp. Could this be the reason for errors I'm experiencing?
