### ISSUE TITLE
Hu

### ISSUE THREAD

**Issue by bhanuvc** [galkahana/HummusJS#102]
Hi,

We are using nodejs in using, we are facing the following error

Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /node_modules/hummus/binding/hummus.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/CRMO/CRMO_Reports/node_modules/hummus/hummus.js:5:31)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/CRMO/CRMO_Reports/helpers/gmailHelper.js:12:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)

Regards
Bhanu

**Comment by galkahana** [comment]
Cent OS 6.5  perhaps?
more data about env plz.

**Comment by galkahana** [comment]
see #88

**Comment by andrejkaurin** [comment]
Yes, it is CentOS 6.5
