### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by talhaanees** [galkahana/HummusJS#162]
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.77/node-v48-win32-x64.ta
r.gz
node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.77 and node@6.10.3 (node-v48 ABI) (falling back to source
compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (G:\assignments\Junior Project\pdfreader\node_modules\npm\node_modules\node-gy
p\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (G:\assignments\Junior Project\pdfreader\node_modules\npm\node_modules\node-gyp
\lib\configure.js:508:16)
gyp ERR! stack     at G:\assignments\Junior Project\pdfreader\node_modules\npm\node_modules\graceful-fs\polyfills.js:284
:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Applications\\Node.js\\node.exe" "G:\\assignments\\Junior Project\\pdfreader\\node_modules\\npm\\n
ode_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=G:\\assignments\\Junior Project\\pd
freader\\node_modules\\hummus\\binding\\hummus.node" "--module_name=hummus" "--module_path=G:\\assignments\\Junior Proje
ct\\pdfreader\\node_modules\\hummus\\binding"
gyp ERR! cwd G:\assignments\Junior Project\pdfreader\node_modules\hummus
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Applications\Node.js\node.exe G:\assignments\Junior Project\pdfread
er\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\assignments\Junior P
roject\pdfreader\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=G:\assignments\Junior Projec
t\pdfreader\node_modules\hummus\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\assignments\Junior Project\pdfreader\node_modules\hummus\nod
e_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "D:\\Applications\\Node.js\\node.exe" "G:\\assignments\\Junior Project\\pdfreader\\node_module
s\\hummus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd G:\assignments\Junior Project\pdfreader\node_modules\hummus
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute 'D:\Applications\Node.js\node.exe G:\assignments\Junior Project\pdfreader\node_modules\npm\node_module
s\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\assignments\Junior Project\pdfreader\node_modules\h
ummus\binding\hummus.node --module_name=hummus --module_path=G:\assignments\Junior Project\pdfreader\node_modules\hummus
\binding' (1)
npm WARN pdfreader@1.0.0 No description
npm WARN pdfreader@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Applications\\Node.js\\node.exe" "D:\\Applications\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "hummus"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! hummus@1.0.77 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.77 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hummus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hummus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hummus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\assignments\Junior Project\pdfreader\npm-debug.log

**Comment by pmcruz8** [comment]
I'm having the same problem as @talhaanees

**Comment by galkahana** [comment]
sais so "gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable."

per this - https://github.com/nodejs/node-gyp

run from command line - npm install --global --production windows-build-tools
and then you should probably be fine

**Comment by talhaanees** [comment]
Tried it, python is there now and all windows-build-tools as well.. But still an error.

node-pre-gyp ERR! Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.77/node-v48-win32-x64.ta
r.gz
node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.77 and node@6.10.3 (node-v48 ABI) (falling back to source
compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "/path/to/executable/python2.7", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (G:\assignments\Junior Project\pdfreader\node_modules\npm\node_modules\node-gy
p\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (G:\assignments\Junior Project\pdfreader\node_modules\npm\node_modules\node-gyp
\lib\configure.js:508:16)
gyp ERR! stack     at G:\assignments\Junior Project\pdfreader\node_modules\npm\node_modules\graceful-fs\polyfills.js:284
:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Applications\\Node.js\\node.exe" "G:\\assignments\\Junior Project\\pdfreader\\node_modules\\npm\\n
ode_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=G:\\assignments\\Junior Project\\pd
freader\\node_modules\\hummus\\binding\\hummus.node" "--module_name=hummus" "--module_path=G:\\assignments\\Junior Proje
ct\\pdfreader\\node_modules\\hummus\\binding" "--python=/path/to/executable/python2.7" "--msvs_version=2015"
gyp ERR! cwd G:\assignments\Junior Project\pdfreader\node_modules\hummus
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'D:\Applications\Node.js\node.exe G:\assignments\Junior Project\pdfread
er\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\assignments\Junior P
roject\pdfreader\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=G:\assignments\Junior Projec
t\pdfreader\node_modules\hummus\binding --python=/path/to/executable/python2.7 --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\assignments\Junior Project\pdfreader\node_modules\hummus\nod
e_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "D:\\Applications\\Node.js\\node.exe" "G:\\assignments\\Junior Project\\pdfreader\\node_module
s\\hummus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd G:\assignments\Junior Project\pdfreader\node_modules\hummus
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok
Failed to execute 'D:\Applications\Node.js\node.exe G:\assignments\Junior Project\pdfreader\node_modules\npm\node_module
s\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=G:\assignments\Junior Project\pdfreader\node_modules\h
ummus\binding\hummus.node --module_name=hummus --module_path=G:\assignments\Junior Project\pdfreader\node_modules\hummus
\binding --python=/path/to/executable/python2.7 --msvs_version=2015' (1)
npm WARN pdfreader@1.0.0 No description
npm WARN pdfreader@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Applications\\Node.js\\node.exe" "D:\\Applications\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "hummus"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! hummus@1.0.77 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.77 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hummus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hummus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hummus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\assignments\Junior Project\pdfreader\npm-debug.log

**Comment by galkahana** [comment]
Well id hate to state the obvious - but theres a statement here saying that python cant be found.

**Comment by cdtinney** [comment]
@talhaanees you need to add the path to python.exe to your Windows PATH variable.

In the docs for [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools), there's an additional argument for this: `--add-python-to-path` that defaults to `false`.

Full command should be:

`npm install --global --production --add-python-to-path windows-build-tools`
