### ISSUE TITLE
Unable to End PDF

### ISSUE THREAD

**Issue by bbogin** [galkahana/HummusJS#186]
Hello,

I'm trying to open a PDF, search for the word "Signature" and place an image over the word in the PDF. 

Here is what I'm doing:
```

var pdfWriter = hummus.createWriterToModify("public/uploads/"+filename, {
      modifiedFilePath: 'public/uploads/signed_'+filename
    });
    console.log(pagesPlacements.length)

for(var i=0;i<pagesPlacements.length;++i) {
      var pageModifier = new hummus.PDFPageModifier(pdfWriter,i);
      var cxt = pageModifier.startContext().getContext();
      pagesPlacements[i].forEach((placement)=> {
        if (placement.text == "Signature") {
              pageModifier.startContext().getContext().drawImage(0, 0, "public/uploads/1502148298996.png");
              pageModifier.endContext().writePage();
              pdfWriter.end();
        }
      })
    };
```

Not sure why everything doesn't look like code, above, but I'm using all of that ^

The error that I'm getting is:

```
TypeError: Unable to end PDF
    at pagesPlacements.(anonymous function).forEach (/Users/ben/Sites/blocksign/blocksign.js:274:25)
    at Array.forEach (native)
    at Object.callback (/Users/ben/Sites/blocksign/blocksign.js:270:26)
    at sendTxCallback (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-core-method/src/index.js:441:29)
    at /Users/ben/Sites/blocksign/node_modules/web3/packages/web3-core-requestmanager/src/index.js:89:9
    at XMLHttpRequest.request.onreadystatechange (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/src/index.js:64:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by galkahana** [comment]
these two are the trouble makers:
              pageModifier.endContext().writePage();
              pdfWriter.end();


writePage() is the end for a pageModifier, so do it just once per page.
pdfWriter.end should happen only once, and it is the end of the pdfWriter.

**Comment by bbogin** [comment]
Hi Gal, thanks for your response.
I see now, I've changed it and the error has changed to something related to callbacks. Do you know what is causing this?

```
    var pdfWriter = hummus.createWriterToModify("public/uploads/"+filename, {
      modifiedFilePath: 'public/uploads/signed_'+filename
    });
    console.log(pagesPlacements.length)

    for(var i=0;i<pagesPlacements.length;++i) {
      var pageModifier = new hummus.PDFPageModifier(pdfWriter,i);
      var cxt = pageModifier.startContext().getContext();
      pagesPlacements[i].forEach((placement)=> {
        if (placement.text == "Signature") {
          pageModifier.startContext().getContext().drawImage(0, 0, "public/uploads/1502148298996.png");    
        }
      })
      pageModifier.endContext().writePage();
    };
    

    pdfWriter.end();
```

Error (pdfWriter.end() is line 279:
```
TypeError: Unable to end PDF
    at Object.callback (/Users/ben/Sites/blocksign/blocksign.js:280:15)
    at sendTxCallback (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-core-method/src/index.js:441:29)
    at /Users/ben/Sites/blocksign/node_modules/web3/packages/web3-core-requestmanager/src/index.js:89:9
    at XMLHttpRequest.request.onreadystatechange (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/src/index.js:64:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/ben/Sites/blocksign/node_modules/web3/packages/web3-providers-http/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by chunyenHuang** [comment]
```bash
    var pdfWriter = hummus.createWriterToModify("public/uploads/"+filename, {
      modifiedFilePath: 'public/uploads/signed_'+filename
    });
    console.log(pagesPlacements.length)
    // pagesPlacements should be the page counts
    for(var i=0;i<pagesPlacements.length;++i) {
      // to avoid page rotation
      // var pageModifier = new hummus.PDFPageModifier(pdfWriter,i, true);
      var pageModifier = new hummus.PDFPageModifier(pdfWriter,i);
      var cxt = pageModifier.startContext().getContext();
      pagesPlacements[i].forEach((placement)=> {
        if (placement.text == "Signature") {
          // change to `cxt`
          // btw, I dont think HummusJS supports png at this moment.
          cxt.drawImage(0, 0, "public/uploads/1502148298996.png");    
        }
      })
      pageModifier.endContext().writePage();
    };
  
    pdfWriter.end();

```

**Comment by bbogin** [comment]
The combination of that and the png was the issue. Thanks!

**Comment by galkahana** [comment]
pngs are now supported
