### ISSUE TITLE
Build error with hummusJS v1.0.85

### ISSUE THREAD

**Issue by ankitrshah89** [galkahana/HummusJS#268]
Hi Gal,

I am using hummusJS v1.0.85 and I get the following error:
```
Error: Cannot find module './PDFRStreamForBuffer'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/package/node_modules/hummus/hummus.js:30:30)
```

Could you please take a look?
Appreciate your help.

Thanks,
Ankit

**Comment by hdlopes** [comment]
The file PDFRStreamForBuffer.js is on the repository but is not included in the NPM package.

**Comment by pavazmo** [comment]
Same issue! It's not included...

**Comment by galkahana** [comment]
oh fuck.
thanks.

**Comment by galkahana** [comment]
k. 1.0.86 should solve this problem.
