### ISSUE TITLE
Pre-built binaries not found for hummus@1.0.86 and node@8.11.1

### ISSUE THREAD

**Issue by Zyphxion** [galkahana/HummusJS#269]
I'm getting this error when attempting to npm -i

It looks like when it falls back to source compile with node-gyp it's then throwing this error:
`Error: EACCES: permission denied, mkdir '<full path redacted>/node_modules/hummus/build'`

This is the correct node_modules directory and I have full read/write control over it, and I am running npm -i with sudo, so I'm not sure what could be going wrong

**Comment by gaganmurghai** [comment]
@Zyphxion @galkahana I am facing same issue. Please help me out.

**Comment by galkahana** [comment]
I verified that the pre built binary for 8.11.1 is there, as well as installed it on my computer and saw that i get it and it doesnt fallback to build.


So, let's start talking environments.

**Comment by Zyphxion** [comment]
What additional info should I provide?

**Comment by bockoblur** [comment]
Hi. I have similar problem, so let me jump in with system info:
**Windows 10.0.16299**
**Node: v8.11.1** (I have node 32bit installed in x64 Windows, but never had any issues with npm packages until now.)
**npm: v5.6.0**

Hope it helps.

```
$ npm i hummus
> hummus@1.0.87 install D:\ionicprojects\nodeqrbatch\node_modules\hummus
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.87/node-v57-win32-ia32.tar.gz
node-pre-gyp WARN Pre-built binaries not found for hummus@1.0.87 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\ionicprojects\\nodeqrbatch\\node_modules\\hummus\\binding\\hummus.node" "--module_name=hummus" "--module_path=D:\\ionicprojects\\nodeqrbatch\\node_modules\\hummus\\binding" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd D:\ionicprojects\nodeqrbatch\node_modules\hummus
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by bockoblur** [comment]
:(
Do you have a particular reason why there are no binaries for Windows? I was reading the documentation last couple of days and it seems that this is THE library for my needs, but I'm mostly in Windows environment. 
Maybe you should accent it somewhere in the documentation that there is no Windows support. Docs just reads: "Available for C++ and NodeJS environments", so I assumed…

**Comment by TiBarification** [comment]
Is there any way to get binaries for windows?

**Comment by galkahana** [comment]
Windows is of course supported. You need to install some build mechanism on your windows env. it's just that the npm install doesn't download prebuilt binaries but rather requires a build on the fly.

see here for instructions:
https://github.com/nodejs/node-gyp#on-windows

**Comment by bockoblur** [comment]
I found that out and it went ok. With a lot of warnings from C++ compiler, but it works great so far.
Thank you!
I have one question about streams. Should I post an issue here (it's not a bug), go to stackoverflow, or do you prefer some other platform for such communication?

**Comment by Zyphxion** [comment]
I'm on OSX 10.13.2, still getting this issue with hummus 1.0.86 and now 1.0.87

Full info from error log:
`node-pre-gyp ERR! Tried to download(undefined): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.86/node-v57-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for hummus@1.0.86 and node@8.11.1 (node-v57 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '<<full path to working directory>>/node_modules/hummus/build'
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=<<full path to working directory>>/node_modules/hummus/binding/hummus.node" "--module_name=hummus" "--module_path=<<full path to working directory>>/node_modules/hummus/binding"
gyp ERR! cwd <<full path to working directory>>/node_modules/hummus
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok `

**Comment by galkahana** [comment]
Maybe not enough disk space? Permissins? Id guess that its not that it cant find the url, just cant write to disk. Simmilarly why cant create folder later when falling back to building

**Comment by jonsanjuan** [comment]
I am on MacOS  Catalina getting similar issues. do you have binaries for MacOSCatalina? 

Here are my errors 
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for hummus@1.0.108 and node@13.8.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hummus/binding' 
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/jonjonsanjuan/Library/Caches/node-gyp/13.8.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/hummus/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/hummus/.node-gyp'
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/hummus/binding/hummus.node" "--module_name=hummus" "--module_path=/usr/local/lib/node_modules/hummus/binding" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd /usr/local/lib/node_modules/hummus
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/hummus/binding/hummus.node --module_name=hummus --module_path=/usr/local/lib/node_modules/hummus/binding --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/hummus/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/lib/node_modules/hummus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/hummus
node-pre-gyp ERR! node -v v13.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/13.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/hummus/binding/hummus.node --module_name=hummus --module_path=/usr/local/lib/node_modules/hummus/binding --napi_version=5 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hummus@1.0.108 install: `node-pre-gyp install --fallback-to-build $EXTRA_NODE_PRE_GYP_FLAGS`
npm ERR! Exit status 1
