### ISSUE TITLE
Error when installing HummusJS on Azure

### ISSUE THREAD

**Issue by mstoldt** [galkahana/HummusJS#285]
I use Hummus Recipe to encrypt PDFs in my Node App. When the HummusJS package installs, it fails to download the tar.gz and instead fallbacks to source compile which works well - up until the end, where this message appears:

`remote:   libpng.vcxproj -> D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\build\Release\\libpng.lib
remote: gyp ERR! build error 
remote: gyp ERR! stack Error: `msbuild` failed with exit code: 1
remote: gyp ERR! stack     at ChildProcess.onExit (D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
remote: gyp ERR! stack     at emitTwo (events.js:106:13)
remote: gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
remote: Failed to execute 'D:\Program Files (x86)\nodejs\6.9.1\node.exe D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\binding --node_abi_napi=node-v48' (1)
remote: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
remote: gyp ERR! System Windows_NT 10.0.14393
remote: gyp ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\Program Files (x86)\\npm\\5.6.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\home\\site\\wwwroot\\node_modules\\hummus-recipe\\node_modules\\hummus\\binding\\hummus.node" "--module_name=hummus" "--module_path=D:\\home\\site\\wwwroot\\node_modules\\hummus-recipe\\node_modules\\hummus\\binding" "--node_abi_napi=node-v48"
remote: gyp ERR! cwd D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus
remote: gyp ERR! node -v v6.9.1
remote: gyp ERR! node-gyp -v v3.6.2
remote: gyp ERR! not ok 
remote: node-pre-gyp ERR! build error 
remote: node-pre-gyp ERR! stack Error: Failed to execute 'D:\Program Files (x86)\nodejs\6.9.1\node.exe D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\binding --node_abi_napi=node-v48' (1)
remote: node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
remote: node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
remote: node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
remote: node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
remote: node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
remote: node-pre-gyp ERR! System Windows_NT 10.0.14393
remote: node-pre-gyp ERR! command "D:\\Program Files (x86)\\nodejs\\6.9.1\\node.exe" "D:\\home\\site\\wwwroot\\node_modules\\hummus-recipe\\node_modules\\hummus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
remote: node-pre-gyp ERR! cwd D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus
remote: node-pre-gyp ERR! node -v v6.9.1
remote: node-pre-gyp ERR! node-pre-gyp -v v0.10.0
remote: node-pre-gyp ERR! not ok 
remote: .
remote: npm WARN rollback Rolling back osenv@0.1.5 failed (this is probably harmless): EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\node_modules\node-pre-gyp\node_modules\nopt\node_modules'
remote: npm WARN rollback Rolling back is-fullwidth-code-point@1.0.0 failed (this is probably harmless): EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules'
remote: npm WARN rollback Rolling back string_decoder@1.1.1 failed (this is probably harmless): EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\node_modules\node-pre-gyp\node_modules\npmlog\node_modules\are-we-there-yet\node_modules\readable-stream\node_modules'
remote: ..........
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! hummus@1.0.87 install: `node-pre-gyp install --fallback-to-build`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the hummus@1.0.87 install script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     D:\local\AppData\npm-cache\_logs\2018-06-01T16_01_08_528Z-debug.log
remote: Failed exitCode=1, command="D:\Program Files (x86)\nodejs\8.9.3\node.exe" "D:\Program Files (x86)\npm\5.6.0\node_modules\npm\bin\npm-cli.js" install --production`

This only happens when committing the changes to Azure, locally it does work. I tries setting the NPM and Node version, installing node-gyp and node-pre-gyp etc. - but nothing seems to work, I always get this error.

Any ideas on how to fix that?

**Comment by phal0r** [comment]
Seems like missing permissions in the file system:
`EPERM: operation not permitted, scandir 'D:\home\site\wwwroot\node_modules\hummus-recipe\node_modules\hummus\node_modules\node-pre-gyp\node_modules\nopt\node_modules'`

**Comment by galkahana** [comment]
try now that we have prebuilt binaries
