### ISSUE TITLE
Error when installing during deploy process

### ISSUE THREAD

**Issue by roelvan** [galkahana/HummusJS#290]
```
Building "hummus@1.0.87" remotely
> Building "hummus@1.0.87" remotely
> Building "hummus@1.0.87" remotely
> Building "hummus@1.0.87" remotely
> Building "hummus@1.0.87" remotely
> Error: Error parsing `package.json` for hummus-1.0.87.tar
>     at extract (/snapshot/ace/lib/extract.js:36:11)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by chunyenHuang** [comment]
Do you mind to post your os and commands?

**Comment by chunyenHuang** [comment]
Not sure if HummusJS supports node 10 yet. https://github.com/galkahana/HummusJS/blob/master/.travis.yml

**Comment by roelvan** [comment]
Got the same error with node v9.
