### ISSUE TITLE
Error during npm install.

### ISSUE THREAD

**Issue by hedonagenda** [galkahana/HummusJS#298]
I am unable to install the package with 
npm install -g hummus
The error from the logs is:
1926 verbose stack Error: hummus@1.0.87 install: `node-pre-gyp install --fallback-to-build`
1926 verbose stack Exit status 1
1926 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
1926 verbose stack     at emitTwo (events.js:126:13)
1926 verbose stack     at EventEmitter.emit (events.js:214:7)
1926 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1926 verbose stack     at emitTwo (events.js:126:13)
1926 verbose stack     at ChildProcess.emit (events.js:214:7)
1926 verbose stack     at maybeClose (internal/child_process.js:925:16)
1926 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1927 verbose pkgid hummus@1.0.87
1928 verbose cwd C:\Users\name\Downloads\lab\data\docs\hummusjs
1929 verbose Windows_NT 10.0.17134
1930 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "hummus"
1931 verbose node v8.9.4
1932 verbose npm  v5.6.0
1933 error code ELIFECYCLE
1934 error errno 1
1935 error hummus@1.0.87 install: `node-pre-gyp install --fallback-to-build`
1935 error Exit status 1
1936 error Failed at the hummus@1.0.87 install script.
1936 error This is probably not a problem with npm. There is likely additional logging output above.
1937 verbose exit [ 1, true ]

The output from the command line is:
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.87/node-v57-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for hummus@1.0.87 and node@8.9.4 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
The system cannot find the path specified.
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\name\\AppData\\Roaming\\npm\\node_modules\\hummus\\binding\\hummus.node" "--module_name=hummus" "--module_path=C:\\Users\\name\\AppData\\Roaming\\npm\\node_modules\\hummus\\binding" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd C:\Users\name\AppData\Roaming\npm\node_modules\hummus
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\name\AppData\Roaming\npm\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:\Users\name\AppData\Roaming\npm\node_modules\hummus\binding --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\name\AppData\Roaming\npm\node_modules\hummus\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\name\\AppData\\Roaming\\npm\\node_modules\\hummus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\name\AppData\Roaming\npm\node_modules\hummus
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\name\AppData\Roaming\npm\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:\Users\name\AppData\Roaming\npm\node_modules\hummus\binding --napi_version=1 --node_abi_napi=napi' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hummus@1.0.87 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.87 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\name\AppData\Roaming\npm-cache\_logs\2018-06-23T13_48_48_779Z-debug.log

**Comment by karpawar** [comment]
**similar problem**, how can it be solved ? 
on Node v10.0.0

> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Tried to download(404): https://hummus.s3-us-west-2.amazonaws.
com/hummus/v1.0.87/node-v64-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for hummus@1.0.87 and node@10.0.0
 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:149:21)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--module=D:\\Karan Pawar\\beacon_wellness\\hcc_backend A6\\hc
c_node_backend\\node_modules\\hummus\\binding\\hummus.node" "--module_name=hummu
s" "--module_path=D:\\Karan Pawar\\beacon_wellness\\hcc_backend A6\\hcc_node_bac
kend\\node_modules\\hummus\\binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd D:\Karan Pawar\beacon_wellness\hcc_backend A6\hcc_node_backend\node
_modules\hummus
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s configure --fallback-to-build --module=D:\Karan Pawar\beacon_wellness\hcc_back
end A6\hcc_node_backend\node_modules\hummus\binding\hummus.node --module_name=hu
mmus --module_path=D:\Karan Pawar\beacon_wellness\hcc_backend A6\hcc_node_backen
d\node_modules\hummus\binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Karan Pawar\beacon_w
ellness\hcc_backend A6\hcc_node_backend\node_modules\hummus\node_modules\node-pr
e-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:236:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Karan Pawar
\\beacon_wellness\\hcc_backend A6\\hcc_node_backend\\node_modules\\hummus\\node_
modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Karan Pawar\beacon_wellness\hcc_backend A6\hcc_node_bac
kend\node_modules\hummus
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node
_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build
 --module=D:\Karan Pawar\beacon_wellness\hcc_backend A6\hcc_node_backend\node_mo
dules\hummus\binding\hummus.node --module_name=hummus --module_path=D:\Karan Paw
ar\beacon_wellness\hcc_backend A6\hcc_node_backend\node_modules\hummus\binding -
-napi_version=3 --node_abi_napi=napi' (1)
npm WARN rollback Rolling back minimist@1.2.0 failed (this is probably harmless)
: EPERM: operation not permitted, scandir 'D:\Karan Pawar\beacon_wellness\hcc_ba
ckend A6\hcc_node_backend\node_modules\rc\node_modules'
npm WARN rollback Rolling back readable-stream@2.3.6 failed (this is probably ha
rmless): EPERM: operation not permitted, rmdir 'D:\Karan Pawar\beacon_wellness\h
cc_backend A6\hcc_node_backend\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hummus@1.0.87 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.87 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in

**Comment by galkahana** [comment]
https://github.com/nodejs/node-gyp#on-windows

**Comment by Gert25** [comment]
I got this same error. I managed to sucsesfuly install the msb-build tools, but still having the same issue. it seem to be failing trying to download the node-v59-win32-x64.tar.gz file on the S3 bucket. Can anyone verify that this file still exist on S3, please. 

See the following console output trying to install hummus on my shitty windows machine:
```
node-pre-gyp WARN Tried to download(404): https://hummus.s3-us-west-2.amazonaws.com/hummus/v1.0.87/node-v59-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for hummus@1.0.87 and node@9.3.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\pdfExample\node_modules\hummus\build\src\deps\PDFWriter\pdfwriter.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" w
as not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\pdfExample\node_modules\hummus\src\deps\LibAesgm\libaesgm.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not f
ound. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\pdfExample\node_modules\hummus\src\deps\FreeType\freetype.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not f
ound. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\pdfExample\node_modules\hummus\src\deps\LibJpeg\libjpeg.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not fou
nd. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\pdfExample\node_modules\hummus\src\deps\ZLib\zlib.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Co
nfirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\pdfExample\node_modules\hummus\src\deps\LibTiff\libtiff.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not fou
nd. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\pdfExample\node_modules\hummus\src\deps\LibPng\libpng.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found
. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Dell\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dell\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\pdfExample\\node_modules\\hummus\\binding\\hummus.node" "--module_name=hummus" "--module_path=C:\\pdfExample\\node_modules\\hummus\\binding" "--napi_version=2" "--node_abi_napi=napi"
gyp ERR! cwd C:\pdfExample\node_modules\hummus
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Dell\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\pdfExample\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:\pdfExample\node_modules\hummus\binding --napi_version=2 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\pdfExample\node_modules\hummus\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\pdfExample\\node_modules\\hummus\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\pdfExample\node_modules\hummus
node-pre-gyp ERR! node -v v9.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Dell\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\pdfExample\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:\pdfExample\node_modules\hummus\binding --napi_version=2 --node_abi_napi=napi' (1)
npm WARN ng2-pdf-viewer@3.0.8 requires a peer of pdfjs-dist@1.9.489 but none is installed. You must install peer dependencies yourself.
npm WARN worker-loader@0.8.1 requires a peer of webpack@>=0.9 <2 || ^2.1.0-beta || ^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package @angular/cli is included as both a dev and production dependency.
npm WARN The package @angular/compiler-cli is included as both a dev and production dependency.
npm WARN The package typescript is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hummus@1.0.87 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.87 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2018-07-13T13_31_33_133Z-debug.log
```

**Comment by grojas7** [comment]
Similar error here.

**Context**:
- GalliumOS
- Node version v8.11.4
- npm 5.8.0

[2018-09-06T23_55_12_940Z-debug.log](https://github.com/galkahana/HummusJS/files/2359077/2018-09-06T23_55_12_940Z-debug.log)
