### ISSUE TITLE
TypeError: Unable to end PDF (Random: out of 10, 5 times I got an error.)

### ISSUE THREAD

**Issue by hrdk108** [galkahana/HummusJS#321]
My Image is in png format. The issue is random. Out of 10, 5 times it gives an error.

```
try{
      var pdfWriter = hummus.createWriterToModify(termCondFilePath, {modifiedFilePath: signedDocFilePath});
      var pageModifier = new hummus.PDFPageModifier(pdfWriter,4,true);
      var ctx = pageModifier.startContext().getContext();
    ctx.drawImage(70,180, imageFilePath, {transformation:{width:150,height:100, proportional:true}});
    pageModifier.endContext().writePage();
    pdfWriter.end();
    if(fs.existsSync(signedDocFilePath)){
      callback(null, "successfully created PDF");
    } else {
      callback("Error while creating document.");
    }
  } catch(e){
    console.log("try....catch.....e.....", e);
    callback(e);
  }
```

Log error:

```
try....catch.....e..... TypeError: Unable to end PDF
    at generateSignedDoc (/Users/hardik.shah/git/BE/fileStream/service/fileStream.js:38:15)
    at Promise.apply (/Users/hardik.shah/git/BE/node_modules/q/q.js:1185:26)
    at Promise.promise.promiseDispatch (/Users/hardik.shah/git/BE/node_modules/q/q.js:808:41)
    at /Users/hardik.shah/git/BE/node_modules/q/q.js:1411:14
    at runSingle (/Users/hardik.shah/git/BE/node_modules/q/q.js:137:13)
    at flush (/Users/hardik.shah/git/BE/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by hrdk108** [comment]
The issue was, `hummus` is processing before fileStream for `png` image get closed. So, I need to to take care about `fstream` close event first and then serve image to hummus. That was not issue from `hummus` library.
