### ISSUE TITLE
Something is wrong,when i upgrade my node to 10x.

### ISSUE THREAD

**Issue by JarvisQJ** [galkahana/HummusJS#330]
````
Error: The module '\\?\E:\formal\server\node_modules\hummus\binding\hummus.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (E:\formal\server\node_modules\hummus\hummus.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (E:\formal\server\node_modules\hummus-recipe\lib\Recipe.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:689:30)

**Comment by ggaabe** [comment]
npm rebuild hummus --build-from-source
is what worked for me

**Comment by YOO629** [comment]
`npm rebuild` and `npm install` didn't work for me in this case. using @ggaabe 's suggestion of `npm rebuild hummus --build-from-source` worked fine

**Comment by galkahana** [comment]
you can also uninstall and reinstall.
problem is that changes in node version may lead to change in underlying binary code. hummus being binary itself, will need a different binary payload to fit the new node version.
