### ISSUE TITLE
TypeError: Unable to start parsing PDF file

### ISSUE THREAD

**Issue by blairjanis** [galkahana/HummusJS#409]
I'm getting this error when trying to createReader ... 

```javascript
var pdfReader = hummus.createReader('bad copy 9.pdf');
```
```
TypeError: Unable to start parsing PDF file
    at Object.<anonymous> (/Users/blairjanis/workspace/node/hummus-test/index.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

I think the issue has to do with a header and a link in the document but I'm not sure how to troubleshoot this.  I've removed sensitive personal data on all the pages but fortunately, the page that seems to be a problem (page 3) does not have personal data on it so I was able to create a version that is broken and am attaching it to this post.

Thanks for you help.  And I'm loving Hummus ... best node pdf package out there!

[not-working.pdf](https://github.com/galkahana/HummusJS/files/3411658/not-working.pdf)

**Comment by kilsen** [comment]
Were you ever able to find a solution or workaround for this? I'm having the same issue with some documents.

**Comment by untrustedlifeswanleap** [comment]
Same, even with proper headers it is failing

**Comment by makinhs** [comment]
same here

**Comment by FranklinThaker** [comment]
Finally, I've created a solution here. 
https://stackoverflow.com/questions/69039978/hummus-recipe-npm-typeerror-unable-to-start-parsing-pdf-file/69040034#69040034
