### ISSUE TITLE
Failing to install Hummus on Windows Server 2012

### ISSUE THREAD

**Issue by frikkievb** [galkahana/HummusJS#51]
Hi,

I am not sure if the problem is me or it is residing somewhere else.  I am unable to install Hummus on our Windows 2012 Server.

This is the message from npm:

```
> hummus@1.0.45 install C:\inetpub\wwwroot\dossier\api\node_modules\hummus
> node-pre-gyp install --fallback-to-build


C:\inetpub\wwwroot\dossier\api\node_modules\hummus>if not defined npm_config_nod
e_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\no
de_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\inetpub\wwwroot\dossier\api\node_modules\hummus>if not defined npm_config_nod
e_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\no
de_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\i
netpub\wwwroot\dossier\api\node_modules\hummus\binding\hummus.node --module_name
=hummus --module_path=C:\inetpub\wwwroot\dossier\api\node_modules\hummus\binding
 )  else (node  configure --fallback-to-build --module=C:\inetpub\wwwroot\dossie
r\api\node_modules\hummus\binding\hummus.node --module_name=hummus --module_path
=C:\inetpub\wwwroot\dossier\api\node_modules\hummus\binding )

C:\inetpub\wwwroot\dossier\api\node_modules\hummus>if not defined npm_config_nod
e_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\no
de_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\inetp
ub\wwwroot\dossier\api\node_modules\hummus\binding\hummus.node --module_name=hum
mus --module_path=C:\inetpub\wwwroot\dossier\api\node_modules\hummus\binding )
else (node  build --fallback-to-build --module=C:\inetpub\wwwroot\dossier\api\no
de_modules\hummus\binding\hummus.node --module_name=hummus --module_path=C:\inet
pub\wwwroot\dossier\api\node_modules\hummus\binding )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\inetpub\wwwroot\dossier\api\node_modules\hummus\build\src\deps\PDFWriter\pdf
writer.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Def
ault.props" was not found. Confirm that the path in the <Import> declaration is
 correct, and that the file exists on disk.
C:\inetpub\wwwroot\dossier\api\node_modules\hummus\src\deps\FreeType\freetype.v
cxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.pro
ps" was not found. Confirm that the path in the <Import> declaration is correct
, and that the file exists on disk.
C:\inetpub\wwwroot\dossier\api\node_modules\hummus\src\deps\LibJpeg\libjpeg.vcx
proj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props
" was not found. Confirm that the path in the <Import> declaration is correct,
and that the file exists on disk.
C:\inetpub\wwwroot\dossier\api\node_modules\hummus\src\deps\ZLib\zlib.vcxproj(2
0,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was
not found. Confirm that the path in the <Import> declaration is correct, and th
at the file exists on disk.
C:\inetpub\wwwroot\dossier\api\node_modules\hummus\src\deps\LibTiff\libtiff.vcx
proj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props
" was not found. Confirm that the path in the <Import> declaration is correct,
and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
ack-to-build" "--module=C:\\inetpub\\wwwroot\\dossier\\api\\node_modules\\hummus
\\binding\\hummus.node" "--module_name=hummus" "--module_path=C:\\inetpub\\wwwro
ot\\dossier\\api\\node_modules\\hummus\\binding"
gyp ERR! cwd C:\inetpub\wwwroot\dossier\api\node_modules\hummus
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=C:\inetpub\wwwroot\dossier\api\node_modules\hummus\binding\hum
mus.node --module_name=hummus --module_path=C:\inetpub\wwwroot\dossier\api\node_
modules\hummus\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\inetpub\wwwroot\doss
ier\api\node_modules\hummus\node_modules\node-pre-gyp\lib\util\compile.js:83:29)

node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\inetpub\\ww
wroot\\dossier\\api\\node_modules\\hummus\\node_modules\\node-pre-gyp\\bin\\node
-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\inetpub\wwwroot\dossier\api\node_modules\hummus
node-pre-gyp ERR! node -v v4.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.13
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\inetpub\ww
wroot\dossier\api\node_modules\hummus\binding\hummus.node --module_name=hummus -
-module_path=C:\inetpub\wwwroot\dossier\api\node_modules\hummus\binding' (1)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "hummus" "--save"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! hummus@1.0.45 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hummus@1.0.45 install script 'node-pre-gyp install --fall
back-to-build'.
npm ERR! This is most likely a problem with the hummus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls hummus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\inetpub\wwwroot\dossier\api\npm-debug.log
```

Please assist!

Kind regards.

**Comment by galkahana** [comment]
Hi,
Do you have a compiler on that server? something like visual studio?

Gal.

**Comment by frikkievb** [comment]
Let me check, and I will get back to you. Thanks so far.

**Comment by frikkievb** [comment]
I've upgraded node to v 4.2.2 on my local machine.  And now I am getting the same error.  I have Visual Studio 2012 installed on my machine.

**Comment by galkahana** [comment]
i'll try this when i get back home and see if i'm getting the same.

**Comment by frikkievb** [comment]
Thank you!

**Comment by galkahana** [comment]
ok. seems to be working well for me. 

Checking out the install log that you attached i see this as an initial bad sign

    error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Googled it, found this:
http://stackoverflow.com/questions/16092169/why-does-msbuild-look-in-c-for-microsoft-cpp-default-props-instead-of-c-progr

try seeing if what they suggest works for you.
Gal

**Comment by frikkievb** [comment]
I will check this out.  Thank you!

**Comment by AnttiVikman** [comment]
I run into similar issues with Windows 10 and found via the link provided by @galkahana this https://github.com/felixrieseberg/windows-build-tools which sorted out the issues for me
